// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctgcaaybpsultttvuvqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0Z2NhYXlicHN1bHR0dHZ1dnFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNDAxNzUsImV4cCI6MjA1NjgxNjE3NX0.930-iapP70dSrp_3TaO9iOC-LkmjZhy7o-EN0yO1zxg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);